version: "3"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - ./.env
        ports:
            - 5000:80
        image: stock-screener:app
