version: "3"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - ./.env
        ports:
            - 5000:5000
        image: stock-screener:app
        stdin_open: true # docker run -i
        tty: true        # docker run -t
